repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black

#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [ python ]
#        args:
#          [
#            "-rn", # Only display messages
#            "-sn", # Don't display the score
#          ]