repos:
- hooks:
  - args:
    - --profile
    - black
    - --filter-files
    id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - id: black
  repo: https://github.com/ambv/black
  rev: 22.12.0
- hooks:
  - args:
    - -rn
    - -sn
    entry: pylint
    exclude: ^src/examples/
    files: ^src/
    id: pylint
    language: system
    name: pylint
    pass_filenames: true
    types:
    - python
  - args:
    - --config-file
    - pyproject.toml
    - --ignore-missing-imports
    entry: mypy
    exclude: ^src/examples/
    files: ^src/
    id: mypy
    language: system
    name: mypy
    types:
    - python
  repo: local
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.12.0
