repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^src/
        pass_filenames: true
        exclude: ^src/examples/
        args:
          - "-rn"
          - "-sn"
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        files: ^src/
        exclude: ^src/examples/
        args:
          - "--config-file"
          - "pyproject.toml"
          - "--ignore-missing-imports"